name: Protocol Land Sync
on:
    push:
        branches:
            - 'main'

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: 'Checkout repo (default branch)'
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0
            - name: 'Checkout all branches'
              run: |
                  git fetch --all
                  for branch in $(git branch -r | grep -v '\->'); do
                      git checkout --track $branch || echo "Branch $branch already exists locally"
                  done
                  git checkout $(git rev-parse --abbrev-ref HEAD)
                  git branch -a
            - name: 'Setup node 18'
              uses: actions/setup-node@v3
              with:
                  node-version: '18.17.0'
            - name: 'Log repo details for debugging'
              run: |
                  echo "Current branch:"
                  git branch
                  echo "All branches:"
                  git branch -a
                  echo "Tracked files:"
                  git ls-files
            - name: 'Install @protocol.land/sync'
              run: npm install @protocol.land/sync
            - name: 'Sync repo to Protocol Land'
              run: |
                  echo "Syncing repository..."
                  npx @protocol.land/sync || echo "Sync failed"
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  REPO_TITLE: ${{ github.event.repository.name }}
                  REPO_DESCRIPTION: ${{ github.event.repository.description }}
                  WALLET: ${{ secrets.WALLET }}
